name: Patch recovery for fastbootd

on:
  workflow_dispatch:
    inputs:
      model:
        description: 'S911U1UEU6AYH9'
        required: true

      recovery_link:
        description: 'https://filebin.net/9s47tjexf87tokck'
        required: true   
              
jobs:
  patch-recovery-revived:
    runs-on: ubuntu-latest
    permissions:
      contents: write    
    steps:
      - name: Checkout source
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          
      - name: Running patch-recovery-revived
        run: |
          GOFILE=1 bash patch-recovery.sh "${{ github.event.inputs.recovery_link }}" "${{ github.event.inputs.model }}"
      
      - name: Uploading Artifact
        uses: actions/upload-artifact@v6
        with:
          name: "Fastbootd-patched-recovery-${{ github.event.inputs.model }}"
          path: output/*.tar
